### PR TITLE
feat: completion for message comments

### PR DESCRIPTION
**Pull request by RedMser**
Autocomplete when writing a comment above a message, automatically fill in all variable references so they can be documented (video is slightly outdated!):

24-05-01_18-35-50_Code_Puffer

I also fixed some typos in the readme :)

### CODE REVIEW

**Comment by macabeus** [comment]
Thanks for the PR!

I was checking if there is a standard way to document the messages, but it seems to be still in WIP (https://github.com/projectfluent/fluent/issues/16 and https://github.com/projectfluent/fluent/issues/140).
Then, I think that your PR is a good kickstart.

But I think that we can add a trigger character to make the autocomplete menu automatically open.
Otherwise, this feature is a bit too hidden, imho.

```diff
- vscode.languages.registerCompletionItemProvider('fluent', completionProvider)
+ vscode.languages.registerCompletionItemProvider('fluent', completionProvider, '#')
```

What do you think about it?

<hr />

Also, while testing this PR, sometimes it throws errors:

```
ERR Cannot read properties of undefined (reading 'groupComments'): TypeError: Cannot read properties of undefined (reading 'groupComments')
	at getGroupComments (/Users/macabeus/ApenasMeu/vscode-fluent/out/src/global-state/index.js:67:54)
```

It may be because it's trying to access `globalState[path]` before it is initialized.

I think it solves this issue well:

```diff
  const getGroupComments = (path: string) =>
-   globalState[path].groupComments
+   globalState[path]?.groupComments ?? []
```

**Comment by RedMser** [comment]
Thanks for your review! Your suggestions sound good. (TIL about trigger characters!)

We can wait until the semantic comments discussion is settled, or merge it in some state and later update when the official syntax is decided upon. I don't mind either way.

As for the code changes, you can either commit them yourself directly if you want, or I can work on them tomorrow and add you as co-author.

**Comment by RedMser** [comment]
Applied your suggested changes, everything seems to work as expected!

**Comment by macabeus** [comment]
Thanks! It's published on the [`v1.1.0` release](https://github.com/macabeus/vscode-fluent/releases/tag/v1.1.0) 🎉

**Pull request merged**
